version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/5.7/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/8.0/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/mariadb-10.2.17/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/mariadb-10.2.23/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/mariadb-latest/"
    schedule:
      interval: "daily"
