version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/5.7/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        versions: [">=8.0"]
  - package-ecosystem: "docker"
    directory: "/8.0/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        versions: [">=8.1"]
  - package-ecosystem: "docker"
    directory: "/mariadb-10.2.17/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        versions: [">=10.2.18"]
  - package-ecosystem: "docker"
    directory: "/mariadb-10.2.23/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "*"
        versions: [">=10.2.24"]
  - package-ecosystem: "docker"
    directory: "/mariadb-latest/"
    schedule:
      interval: "daily"
